language: python
python:
  - "3.5"
  - "3.6"
# command to install dependancies
install: "pip install -r DataHandling/requirements.txt"
install: "pip install -e ."
# command to run tests
script: pytest --cov=DataHandling -v --mpl